- src/Extension/CwpControllerExtension.php
- src/Model/CwpSearchIndex.php
Since the search boost extension lives in the cwp/cwp module, we should check if the class exists before using it in logic.
Issue: #1
> FIX Update Subsite namespace and ensure search boost extension exists before checking for its use

- _config.php
This pull request:
* Adds variable definitions into a closure (as other core \_config.php files do) to prevent creating global variables
* Adds the missing `insertButtonsAfter` calls for ssmedia and ssembed for the asset admin plugins (see `asset-admin/_config.php`)
Fixes #17
> FIX Ensure media and embed TinyMCE plugin buttons are shown in the toolbar

- README.md
- src/Control/InitialisationMiddleware.php
- tests/Control/InitialisationMiddlewareTest.php
[FEAT] Add 'X-XSS-Protection: 1; mode=block' header by default to all CWP projects, with option to disable
[DOCS] Add documentation for the configurable values (xss_protection_disabled, egress_proxy_default_enabled and egress_proxy_exclude_domains)
> [FEAT] Add 'X-XSS-Protection: 1; mode=block' header by default

- README.md
- src/Control/InitialisationMiddleware.php
- tests/Control/InitialisationMiddlewareTest.php
Switches out `xss_protection_disabled` for `xss_protection_enabled` for a more positive developer experience ;-)
Follow on from @chillu's comment on #25.
> Increase API positivity by using xss_protection_enabled

- tests/Control/InitialisationMiddlewareTest.php
This module and cwp/cwp-recipe-core recipe don't include the CMS, and the errorpage module is included by recipe-cms so this breaks the tests when it tries to render a 404 on `/test`. `Security/*` is a framework path, so is safer to use for testing
> Use a framework-safe URL in XSS header tests when no CMS is installed

- _config/documentconverter.yml
Currently this default is non-functional, and e.g. the URL gets set to
```
`DOCVERT_URL`
```
which clearly is not a URL, nor even a valid domain.
As this docvert prioritises config over environment, this makes a mess of any attempts to import data by making the docvert server unreachable.
> FIX Remove attempt to import environment into config for docvert

- _config/extensions.yml
> FIX LoginAttemptNotifications extension is now disabled again, as it is in CWP 1.x

- _config/logging.yml
As @madmatt pointed out, debugged and solved in #43, this change was somehow missed while upgrading from CWP 1.x to 2.x.
Resolves #43
> FIX SilverStripe debug logs and higher are now routed correctly to syslog (Graylog)

- _config/config.yml
Part of #40
This adjusts the default session timeout (cookie) to the default `session.gc_maxlifetime` timeout in PHP configuration on CWP.
> FIX Updating default session timeout to CWP default for consistency

- _config.php
- _config/security.yml
- tests/PasswordStrengthTest.php
and out of _config.php
i.e. use Injector rather than proceedural boot time code, as
SilverStripe 4 supports this (where 3 did not).
Re-introduce some security level settings that were lost at some point
with no clear reason as to why.
Fixes #52
> move PasswordValidator configuration into _config

- _config/extensions.yml
- _config/version.yml
- css/custom.css
- src/Extension/CWPVersionExtension.php
- templates/SilverStripe/Admin/Includes/LeftAndMain_MenuToggle.ss
- tests/Extension/CWPVersionExtensionTest.php
This reinstates the missing version provider configuration. I don't know where this went, but it was introduced in CWP 1.9 and should have been in CWP 2.x.
Fixes #57 
This is what it looks like now: 
Previously the version number wasn't shown until you hovered over the logo, which would then say `SilverStripe (Version - CWP: 2.2.x-dev)`. With the redesigned help menu, it might be misleading to have `2.2` next to `SilverStripe`. I [previously asked](https://github.com/silverstripe/silverstripe-admin/pull/615#issuecomment-427324114) whether we should change this to "CWP" for CWP, but we decided not to.
@clarkepaul @sachajudd might need your input here before this gets merged
> FIX Re-instate CWP recipe version in help menu

- .travis.yml
- src/Control/InitialisationMiddleware.php
- tests/Control/InitialisationMiddlewareTest.php
This commit it based on changing the order of execution in InitialisationMiddleware.
It proposes to change the setting of the environment variables for `http_proxy`, `https_proxy` and `NO_PROXY` from `Environment::setEnv()` back to `putenv()` as it was in CWP1.
As described in the documentation of InitialisationMiddleware its main purpose is to configure the proxy so it is automatically picked up when calling `curl` in an apache context.
I'm aware of the multithreaded issue described in https://github.com/laravel/framework/issues/7354, but considering that these variables should be present anyway, I don't consider that to be an issue in context of CWP.  Maybe @tractorcow has some insights into that?
Otherwise the variables are redundant as `SS_OUTBOUND_PROXY`, `SS_OUTBOUND_PROXY_PORT` and …
> Use putenv() in InitialisationMiddleware

- src/Control/CwpBasicAuthMiddleware.php
- tests/Control/CwpBasicAuthMiddlewareTest.php
Fixes https://github.com/silverstripe/cwp-core/issues/64
> FIX CwpBasicAuthMiddleware::setWhitelistedIps() now accepts comma delimited IP lists within an array of values

- .travis.yml
- _config/encryptors.yml
- composer.json
- src/PasswordEncryptor/PBKDF2.php
- tests/PasswordEncryptor/PBKDF2Test.php
This also updates the core constraints to SilverStripe 4.5, which requires PHP 7.1, and updates the Travis build matrix to match.
Resolves #51
> NEW Add PBKDF2 PasswordEncryptor with SHA-512 as the default algorithm for NZISM compliance

- src/Control/InitialisationMiddleware.php
- tests/Control/InitialisationMiddlewareTest.php
See https://github.com/silverstripe/cwp-installer/issues/24.
Can't configure this by default since it would violate semver.
Added to the cwp-core because that's a context where we can safely assume
valid SSL operation in test and production environments.
Added to PHP rather than htaccess since we can't assume SSL is available
on dev environments, and it'll be a really annoying blocker for devs to track down.
Added to InitialisationMiddleware since it's already modifying HTTP headers (`X-XSS-Protection`).
This isn't ideal, since it conflicts with guidance on our wider open source docs:
https://docs.silverstripe.org/en/4/developer_guides/security/secure_coding/.
But I'd say this guidance is outdated, adding headers in a specific
controller doesn't provide enough coverage. And in the case of …
> NEW Opt-in HTTP Strict Transport Headers

- _config/textextraction.yml
This fixes issue #74 to re-enable cwp specific config for silverstripe/textextraction and use class `SilverStripe\TextExtraction\Cache\FileTextCache\Cache` instead of the current configuration of https://github.com/silverstripe/cwp-core/blob/1108756119fd36790ba1ecd30076c555eb3075f2/_config/textextraction.yml#L8 
This means FileTextCaching is used instead of caching extracted text in the database as it is the fallback right now and is different to the SilverStripe 3 compatible versions.
> Fix cwptextextraction config (issue #74) 

- src/PasswordEncryptor/PBKDF2.php
This will result in a 3x increase in compute time for generation / verification of passwords. Since authenticating a user is a fairly infrequent activity (compared to the volume of other requests), this should be an acceptable trade-off.
> Increase iterations used by PBKDF2 per security recommendation

- src/Control/InitialisationMiddleware.php
The syntax for the HSTS related 'max-age' is incorrect, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
Parent issue: https://github.com/silverstripe/cwp-installer/issues/29
Related: https://github.com/silverstripe/cwp-installer/pull/31
> BUG max-age syntax in comments is incorrect

- .travis.yml
- _config/textextraction.yml
This is a cherry-pick of previous commit to 2 that went into 2.3 though not 2.2
https://github.com/silverstripe/cwp-core/commit/192dcaebdc07351fa5ce198ab9449e861171367d
It's to fix this test in cwp-recipe-kitchen-sink
https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/jobs/625881938
Basically what was happening is that an extra version of a File was being written though not published, so a logged out $file->canView() check was failing because the draft version was 3 while the live version was 2
> Update textextraction config

- _config/security.yml
This was preventing MFA Account Resets on UAT environments.
> FIX Add resetaccount route to basic auth exceptions
